// Perlin Noise Terrain
// Muntaha Chowdhury
// Oct 1, 2024
// A terrain generated by Noise with a flag/panning/average/changeable + 2D Noise

let timeAtTerrain;
let advanceTimeBy = 0.01;
let terWidth = 5;
let tallestY = 0;
let tallestX = 0;
let terHeights = [];
let avg;

function setup() {
  createCanvas(windowWidth, windowHeight);
  // frameRate(1);
}

function draw() {
  background(220);
  generateTerrain();
  timeAtTerrain = frameCount/100;
}

function generateTerrain() {
  strokeWeight(1);
  stroke(0);
  fill(100);
  tallestY = 0;
  avg = 0;

  for (let block = 0; block < width; block+=terWidth) {

    let terHeight = noise(timeAtTerrain);
    terHeight = map(terHeight, 0, 1, 10, height/2);
    terHeights.push(terHeight);

    rect(block, height, terWidth, -terHeight)
    if (terHeight > tallestY)  {
      tallestY = terHeight;
      tallestX = block;
    }
    timeAtTerrain += advanceTimeBy;

  }

  drawFlag(tallestX, tallestY);
  drawAvg();
}


function keyPressed() {
  if (keyCode === RIGHT_ARROW) terWidth += 2;
  if (keyCode === LEFT_ARROW) terWidth -=2;
  if (terWidth < 1) terWidth = 1;
}


function drawFlag(x, y) {
  strokeWeight(3);
  line(x, height-y, x, height-(y+30));
  fill(100);
  triangle(x, height-(y+30), x, height-(y+20), x+10, height-(y+25))
}

function drawAvg() {
  for (let i = 0; i < terHeights.length; i++) {
    avg += i;
  }
  avg = avg/terHeights.length;

  // line(0, avg, width, avg);
  // console.log(avg);
  terHeights = [];
}